### ISSUE TITLE
How do I close a server in nitronet?

### ISSUE THREAD

**Issue by KittyCatCode** [baseball435/NitroNet#4]
I'm making a very simple server GUI, with a status at the top, and off and on buttons at the bottom. However, when I started making the listener for the off button, there didn't seem to be a method to close the server in the Server class. How do I close the server?

**Comment by jmrapp1** [comment]
The Server class has a [close method](https://github.com/baseball435/NitroNet/blob/master/src/com/jmr/wrapper/server/Server.java#L128) which will close the server.
