### ISSUE TITLE
You should use Gradle or Maven as your project structure

### ISSUE THREAD

**Issue by jasons2000** [baseball435/NitroNet#5]
You should use Gradle or Maven as your project structure, these are pretty standard

**Comment by Isfirs** [comment]
@jasons2000 I don't know about your skills, but I did what you should have done: make a fork and add a pull request.

For the moment, clone the repo located at my page, download and just `mvn install` to install it into your local repository.

Can be closed.

**Comment by jasons2000** [comment]
thanks, haven't done a pull request before, still getting used to github. Can I ask why you've gone with maven instead of gradle? I've used Maven extensively in the past and like it apart from the XML syntax.

**Comment by Isfirs** [comment]
No particular reason.

I just use maven alot in production and if we don't change to gradle here, I don't think of going there myself. 

If you are used to gradle, i recommend reading the [Fork](https://help.github.com/articles/fork-a-repo/) and [Pull Request](https://help.github.com/articles/using-pull-requests/) docs and make one yourself. Maybe wait until he accepted the pull request. I don't know how that will react if you fork my fork nad add a pull request there (for the fork of my fork)

**Comment by Isfirs** [comment]
I assume this is closed.

**Comment by jmrapp1** [comment]
I will add gradle and maven support ASAP. Sorry for the temporary inconvenience .
